config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registration: 'users/registrations',
                                    sessions: 'users/sessions'}
  resources :users, :only => [:index, :show]
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :volunteers
  root 'volunteers#index'

 

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
    belongs_to :user

    scope :search, -> (search_params) do
        return if search_params.blank?

        do_from(search_params[:do_from])
        .do_to(search_params[:do_to])
        .area_like(search_params[:area])
    end


    scope :do_from, -> from {
        Volunteer.where('? <= do_on', from) if from.present?
    }

    scope :do_to, -> to {
        Volunteer.where('do_on <= ?', to) if to.present?
    }

    scope :area_like, -> area {
        Volunteer.where(area: "#{area}") if area.present?
    }

    enum area_number:{
        " ":0,
        北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
        茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
        新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
        岐阜県:21,静岡県:22,愛知県:23,三重県:24,
        滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
        鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
        徳島県:36,香川県:37,愛媛県:38,高知県:39,
        福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
        沖縄県:47
    }

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index
        @search_params = volunteer_search_params
        @volunteers = Volunteer.search(@search_params).includes(:user)
    end


    def new
        @volunteer = Volunteer.new
    end


    def create
        @volunteer = Volunteer.new(volunteer_params)
        
        @volunteer.user_id = current_user.id

        if @volunteer.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show 
        @volunteer = Volunteer.find(params[:id])

        
    end

    def edit
        @volunteer = Volunteer.find(params[:id])
    end

    def update
        volunteer = Volunteer.find(params[:id])
        if volunteer.update(volunteer_params)
          redirect_to :action => "show", :id => volunteer.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        volunteer = Volunteer.find(params[:id])
        volunteer.destroy
        redirect_to action: :index
    end

    private
    def volunteer_params
        params.require(:volunteer).permit(:title, :do_on, :area, :gender, :from_area, :text)
    end

    def volunteer_search_params
        params.fetch(:search, {}).permit(:do_from, :do_to, :area)
    end


end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/edit.html.erb
<div class="volunteers-container">
  <div class="volunteer">
    <div class="flex-container">
      <%= form_for @volunteer do |f| %>
        <div class="field">
          <%= f.label :タイトル %>
          <%= f.text_field :title, :size => 30 %>
        </div>

        <div class="field">
          <%= f.label :日付 %>
          <%= f.date_field  :do_on %>
        </div>

        <div class="field">
         <%= f.label :地域 %>
          <%= f.select :area, Volunteer.area_numbers.keys, {} %>
        </div>

        <div class="field">
          <%= f.label :希望する性別 %>
          <%= f.select :gender, 
            [[" ", " "],
             ["女性","女性"],
             ["男性","男性"]] %>
        </div>

        <div class="field">
          <%= f.label :応募者の地域 %>
          <%= f.select :from_area, Volunteer.area_numbers.keys, {} %>
        </div>

        <div class="field">
          <%= f.label :募集内容 %>
          <%= f.text_area :text, :size => "30x2" %>
        </div>
        <div class="actions">
          <%= f.submit "Edit", class: "post-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/volunteers/index.html.erb
<div class="search">
  <%= form_with(scope: :search, url: volunteers_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label :do_on, "day" %>
      <%= f.date_field :do_from, value: @search_params[:do_from] %> -
      <%= f.date_field :do_to, value: @search_params[:do_to] %>
    </div>

    <div class="field">
      <%= f.label :area, "area" %>
      <%=  f.select :area, Volunteer.area_numbers.keys, {} , value: @search_params[:area]%>
      <%= f.submit 'search', class: "button" %>
    </div>
  <% end %>
</div>


<div class="volunteers-container">
  <% @volunteers.each do |t| %>
    <div class="volunteer">
      <div class="flex-container">
        <div class="title">
          <h3><%= t.title %></h3>
        </div>
        <div class="field">
          <div>
            <div>
              <div class="col-1">day</div>
              <div class="col-2"><%= t.do_on %></div>
            </div>
            <div>
              <div class="col-1">area</div>
              <div class="col-2"><%= t.area %></div>
            </div>
            <div>
              <div class="col-1">gender</div>
              <div class="col-2"><%= t.gender %></div>
            </div>
            <div>
              <div class="col-1">from</div>
              <div class="col-2"><%= t.from_area %></div>
            </div>  
          </div>
        </div>
        <div class="right">
          <p><%= link_to "more...", volunteer_path(t.id) %></p>
          <p><%= t.created_at.to_s(:datetime_jp) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/volunteers/new.html.erb
<div class="volunteers-container">
  <div class="volunteer">
    <div class="flex-container">
      <%= form_for @volunteer do |f| %>
        <div class="field">
          <%= f.label :タイトル %>
          <%= f.text_field :title, :size => 30 %>
        </div>

        <div class="field">
          <%= f.label :日付 %>
          <%= f.date_field  :do_on %>
        </div>

        <div class="field">
          <%= f.label :地域 %>
          <%= f.select :area, Volunteer.area_numbers.keys, {} %>
        </div>

        <div class="field">
          <%= f.label :希望する性別 %>
          <%= f.select :gender, 
          [[" ", " "],
           ["女性","女性"],
           ["男性","男性"]] %>
        </div>

        <div class="field">
          <%= f.label :応募者の地域 %>
          <%= f.select :from_area, Volunteer.area_numbers.keys, {} %>
        </div>

        <div class="field">
          <%= f.label :募集内容 %>
          <%= f.text_area :text, :size => "30x2" %>
        </div>
        <div class="actions">
          <%= f.submit "Post", class: "post-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/volunteers/show.html.erb
<div class="volunteers-container">
  <div class="volunteer">
    <div class="flex-container">
      <div class="title">
        <h3><%= @volunteer.title %></h3>
      </div>
      <div class="field">
        <div>
          <div class="col-1">day</div>
          <div class="col-2"><%= @volunteer.do_on %></div>
        </div>
        <div>
          <div class="col-1">area</div>
          <div class="col-2"><%= @volunteer.area %></div>
        </div>
        <div>
          <div class="col-1">gender</div>
          <div class="col-2"><%= @volunteer.gender %></div>
        </div>
        <div>
          <div class="col-1">from</div>
          <div class="col-2"><%= @volunteer.from_area %></div>
        </div>
        <br/>  
        <p><%= @volunteer.text %></p>
      </div>

      <div class="right">
        <p><a href="/users/<%= @volunteer.user.id %>"><%= @volunteer.user.name %></a></p>
        <% if user_signed_in? && current_user.id == @volunteer.user_id %>  
    　    <p><%= link_to "Edit", edit_volunteer_path(@volunteer.id) %>
    　    <%= link_to "Delete", volunteer_path(@volunteer.id), method: :delete %></p>
        <% end %>
        <p><%= @volunteer.created_at.to_s(:datetime_jp) %></p>
      </div>
    </div>
  </div>
</div>