config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registration: 'users/registrations',
                                    sessions: 'users/sessions'}
  resources :users, :only => [:index, :show]
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :volunteers
  root 'volunteers#index'

 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :volunteers, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: {maximum: 200}

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def index
    @entries_1 = Entry.all
    @entries_2 = Entry.where.not(user_id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %>
<div class="sign-up-in">
        <div class="field">
            <div class="col-1">Name</div>
            <div class="col-2"><%= current_user.name %></div>
        </div>
        <div class="field">
            <div class="col-1">E-mail</div>
            <div class="col-2"><%= current_user.email %></div>
        </div>
        <div class="field">
            <div class="col-1">Profile</div>
            <div class="col-2"><%= current_user.profile%></div>
        </div>
        <div class="right">
            <%= link_to "編集する", edit_user_registration_path %>
        </div>
</div>
<div class="field">
    <h3>DM</h3><br/>
    <% @entries_1.each do |e| %>
        <% @entries_2.each do |f| %>
            <% if (e.user_id == current_user.id) && (e.room_id == f.room_id) %>
                <p> <%= link_to room_path(f.room.id) do %>
                        <%= f.user.name %><br>
                    <% end %>
                </p>
            <% end %>
        <% end %>
    <% end %>
</div>
<% end %>

app/views/users/show.html.erb
<div class="sign-up-in">
  <div class="field">
    <div class="col-1">Name</div>
    <div class="col-2"><%= @user.name %></div>
  </div>
  <div class="field">
    <div class="col-1">Profile</div>
    <div class="col-2"><%= @user.profile %></div>
  </div>
  <div class="field">
    <% if @user.id == current_user.id %>

    <% else %>
      <% if @isRoom == true %>
        <p><a href="/rooms/<%= @roomId %>">DM</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "DM" %>
        <% end %>
      <% end %>
    <% end %>
    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
  </div>
</div>

<div class="volunteers-container">
  <% @user.volunteers.each do |t| %>  
    <div class="user-volunteer">
      <div class="flex-container">
        <div class="title">
          <h3><%= t.title %></h3>
        </div>
      <div class="field">
        <div>
          <div class="col-1">day</div>
          <div class="col-2"><%= t.do_on %></div>
        </div>
        <div>
          <div class="col-1">area</div>
          <div class="col-2"><%= t.area %></div>
        </div>
        <div>
          <div class="col-1">gender</div>
          <div class="col-2"><%= t.gender %></div>
        </div>
        <div>
          <div class="col-1">from</div>
          <div class="col-2"><%= t.from_area %></div>
        </div>
        <br/>  
        <p><%= t.text %></p>
      </div>
      <div class="right">
        <p><a href="/users/<%= @user.id %>"><%= @user.name %></a></p>
        <p><%= t.created_at.to_s(:datetime_jp) %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>