config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registration: 'users/registrations',
                                    sessions: 'users/sessions'}
  resources :users, :only => [:index, :show]
  
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :volunteers
  root 'volunteers#index'

 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>For Others</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <header>
      <h1><%= link_to "For Others", volunteers_path %></h1>
      <div class="header-list">
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Post", new_volunteer_path %></li>
          <li><%= link_to "My Page", users_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
      </div>
    </header>
    
    <main>
      <%= yield %>
    </main>

    <footer>
     <p></p>
    </footer>
  </body>
</html>